openapi: 3.0.0
info:
  title: Cat Breed finding service
  description: A simple express server application that returns the top 5 cat breeds that are child friendly, stranger friendly and dog friendly (each of these have equal weighting).
  version: 0.1.9
servers:
  - url: http://localhost:3000
    description: Development Server
  - url: http://prod-api.example.com
    description: Optional server description, e.g. Production server
paths:
  /cat-breeds/top-five:
    get:
      summary: Returns a list of top five cat breeds based on the type.
      description: Returns a list of top five cat breeds based on the type provided in the query string. The types can be one of child_friendly, stranger_friendly and dog_friendly or combined.
      parameters:
        - in: query
          name: type
          required: true
          schema:
            type: string
          description: The types can be one of `child_friendly`, `stranger_friendly`, `dog_friendly` or `combined`
      responses:
        '200':    # status code
          description: A JSON array of cat breeds
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                example: [{"weight":{"imperial":"7  -  10","metric":"3 - 5"},"id":"abys","name":"Abyssinian","cfa_url":"http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx","vetstreet_url":"http://www.vetstreet.com/cats/abyssinian","vcahospitals_url":"https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian","temperament":"Active, Energetic, Independent, Intelligent, Gentle","origin":"Egypt","country_codes":"EG","country_code":"EG","description":"The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.","life_span":"14 - 15","indoor":0,"lap":1,"alt_names":"","adaptability":5,"affection_level":5,"child_friendly":3,"dog_friendly":4,"energy_level":5,"grooming":1,"health_issues":2,"intelligence":5,"shedding_level":2,"social_needs":5,"stranger_friendly":5,"vocalisation":1,"experimental":0,"hairless":0,"natural":1,"rare":0,"rex":0,"suppressed_tail":0,"short_legs":0,"wikipedia_url":"https://en.wikipedia.org/wiki/Abyssinian_(cat)","hypoallergenic":0,"reference_image_id":"0XYvRd7oD","image":{"id":"0XYvRd7oD","width":1204,"height":1445,"url":"https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg"}}]
        '400':
          description: Bad request. Type should be one of `child_friendly`, `stranger_friendly`, `dog_friendly` or `combined`
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message